---
- hosts: backend
  become: true
  gather_facts: false

  tasks:
    - name: create app group
      group:
        name: "{{ service }}"
        state: present

    - name: create app user
      user:
        name: "{{ service }}"
        groups: "{{ service }}"
        shell: /sbin/nologin
        append: yes
        state: present
        create_home: yes

    - name: Copy systemd service file to server
      template:
        src: templates/app.service.j2
        dest: "/etc/systemd/system/{{ service }}.service"
        owner: root
        group: root
